FROM build_carry

RUN pacman -Sy --noconfirm python2 gnutls python

WORKDIR /tmp

RUN app=samba-4.5.0 \
    && export PYTHON=/usr/bin/python2 \
    && curl -L "https://download.samba.org/pub/samba/stable/${app}.tar.gz" | tar -zx \
    && cd ${app} \
    && ./configure --prefix=/opt/apps/samba \
    && make -j $(nproc) && make install \
    && cd ../ && rm -rf ${app}

WORKDIR /

CMD [ "/opt/apps/samba", "samba.tar.gz" ]
